version: "3.8"
services:
  nats:
    container_name: n1
    image: nats:2.9.16-alpine3.17
    command: --name N1 --cluster_name NATS -m 8222 --js --sd /var/lib/nats/data --cluster nats://0.0.0.0:4245 --routes nats://n1.nats.net:4245,nats://n2.nats.net:4245,nats://n3.nats.net:4245 -p 4222
    volumes:
      - 'jsdata:/var/lib/nats/data'
      - ./shared/hosts:/etc/hosts
    networks:
      nats:
        ipv4_address: 172.10.10.60
    ports:
      - "4222:4222"
      - "8222:8222"
  nats-1:
    container_name: n2
    image: nats:2.9.16-alpine3.17
    command: --name N2 --cluster_name NATS --js --sd /var/lib/nats/data --cluster nats://0.0.0.0:4245 --routes nats://n1.nats.net:4245,nats://n2.nats.net:4245,nats://n3.nats.net:4245 -p 4222
    volumes:
      - 'jsdata:/var/lib/nats/data'
      - ./shared/hosts:/etc/hosts
    networks:
      nats:
        ipv4_address: 172.10.10.61
    ports:
      - "4223:4222"
    depends_on: ["nats"]
  nats-2:
    container_name: n3
    image: nats:2.9.16-alpine3.17
    command: --name N3 --cluster_name NATS --js --sd /var/lib/nats/data --cluster nats://0.0.0.0:4245 --routes nats://n1.nats.net:4245,nats://n2.nats.net:4245,nats://n3.nats.net:4245 -p 4222
    volumes:
      - 'jsdata:/var/lib/nats/data'
      - ./shared/hosts:/etc/hosts
    networks:
      nats:
        ipv4_address: 172.10.10.62
    ports:
      - "4224:4222"
    depends_on: ["nats"]
volumes:
  jsdata:
networks:
  nats:
    ipam:
      driver: default
      config:
        - subnet: "172.10.10.0/24"

