version: "3.8"
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: itsasecret
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './schemas:/docker-entrypoint-initdb.d'
    networks:
      postgres.net:
        ipv4_address: 172.10.11.2
volumes:
  pgdata:
networks:
  postgres.net:
    ipam:
      driver: default
      config:
        - subnet: "172.10.11.0/24"



